### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by Spookakra** [jwansek/eda.gay#3] opened 2022-11-21 13:33 UTC
i am very disappointed

**Comment by jwansek** [comment] 2022-11-22 00:13
the website was down because i was re-configuring my nginx server so its inside docker now

for now the site is available at http://eda.gay (without HTTPS)

i will close the issue once HTTPS has been set up too

**Comment by jwansek** [comment] 2022-11-22 17:52
https is back, so the issue is closed. i how use docker for my nginx and certbot too. 

see https://git.eda.gay/nginx-sites/ (mirror https://github.com/jwansek/nginx-sites)

**Closed as completed by jwansek** 2022-11-22 17:52 UTC
